// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Alerts.Active.Area.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Alerts.Active.Area
{
    /// <summary>
    /// Builds and executes requests for operations under \alerts\active\area
    /// </summary>
    public class AreaRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaDemo.Clients.WeatherApi.alerts.active.area.item collection</summary>
        /// <param name="position">State/area ID</param>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.Area.Item.WithAreaItemRequestBuilder"/></returns>
        public KiotaDemo.Clients.WeatherApi.Alerts.Active.Area.Item.WithAreaItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("area", position);
                return new KiotaDemo.Clients.WeatherApi.Alerts.Active.Area.Item.WithAreaItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.Area.AreaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AreaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/alerts/active/area", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.Area.AreaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AreaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/alerts/active/area", rawUrl)
        {
        }
    }
}
