// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Aviation.Cwsus
{
    /// <summary>
    /// Builds and executes requests for operations under \aviation\cwsus
    /// </summary>
    public class CwsusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaDemo.Clients.WeatherApi.aviation.cwsus.item collection</summary>
        /// <param name="position">NWS CWSU ID</param>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item.WithCwsuItemRequestBuilder"/></returns>
        public KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item.WithCwsuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("cwsuId", position);
                return new KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item.WithCwsuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.CwsusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CwsusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation/cwsus", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.CwsusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CwsusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation/cwsus", rawUrl)
        {
        }
    }
}
