// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Offices.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Offices
{
    /// <summary>
    /// Builds and executes requests for operations under \offices
    /// </summary>
    public class OfficesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaDemo.Clients.WeatherApi.offices.item collection</summary>
        /// <param name="position">NWS office ID</param>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Offices.Item.WithOfficeItemRequestBuilder"/></returns>
        public KiotaDemo.Clients.WeatherApi.Offices.Item.WithOfficeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("officeId", position);
                return new KiotaDemo.Clients.WeatherApi.Offices.Item.WithOfficeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Offices.OfficesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OfficesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/offices", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Offices.OfficesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OfficesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/offices", rawUrl)
        {
        }
    }
}
