// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Zones.Forecast.Item.Observations;
using KiotaDemo.Clients.WeatherApi.Zones.Forecast.Item.Stations;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Zones.Forecast.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \zones\forecast\{zoneId}
    /// </summary>
    public class WithZoneItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The observations property</summary>
        public KiotaDemo.Clients.WeatherApi.Zones.Forecast.Item.Observations.ObservationsRequestBuilder Observations
        {
            get => new KiotaDemo.Clients.WeatherApi.Zones.Forecast.Item.Observations.ObservationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stations property</summary>
        public KiotaDemo.Clients.WeatherApi.Zones.Forecast.Item.Stations.StationsRequestBuilder Stations
        {
            get => new KiotaDemo.Clients.WeatherApi.Zones.Forecast.Item.Stations.StationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Zones.Forecast.Item.WithZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithZoneItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zones/forecast/{zoneId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Zones.Forecast.Item.WithZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithZoneItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zones/forecast/{zoneId}", rawUrl)
        {
        }
    }
}
