// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.Item;
using KiotaDemo.Clients.WeatherApi.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaDemo.Clients.WeatherApi.Aviation.Sigmets
{
    /// <summary>
    /// Builds and executes requests for operations under \aviation\sigmets
    /// </summary>
    public class SigmetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaDemo.Clients.WeatherApi.aviation.sigmets.item collection</summary>
        /// <param name="position">ATSU identifier</param>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.Item.WithAtsuItemRequestBuilder"/></returns>
        public KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.Item.WithAtsuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("atsu", position);
                return new KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.Item.WithAtsuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SigmetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation/sigmets{?atsu*,date*,end*,sequence*,start*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SigmetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation/sigmets{?atsu*,date*,end*,sequence*,start*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of SIGMET/AIRMETs
        /// </summary>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Models.SigmetCollectionGeoJson"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaDemo.Clients.WeatherApi.Models.ProblemDetail">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaDemo.Clients.WeatherApi.Models.SigmetCollectionGeoJson?> GetAsync(Action<RequestConfiguration<KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder.SigmetsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaDemo.Clients.WeatherApi.Models.SigmetCollectionGeoJson> GetAsync(Action<RequestConfiguration<KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder.SigmetsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", KiotaDemo.Clients.WeatherApi.Models.ProblemDetail.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaDemo.Clients.WeatherApi.Models.SigmetCollectionGeoJson>(requestInfo, KiotaDemo.Clients.WeatherApi.Models.SigmetCollectionGeoJson.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of SIGMET/AIRMETs
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder.SigmetsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder.SigmetsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/geo+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of SIGMET/AIRMETs
        /// </summary>
        public class SigmetsRequestBuilderGetQueryParameters 
        {
            /// <summary>ATSU identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("atsu")]
            public string? Atsu { get; set; }
#nullable restore
#else
            [QueryParameter("atsu")]
            public string Atsu { get; set; }
#endif
            /// <summary>Date (YYYY-MM-DD format)</summary>
            [QueryParameter("date")]
            public Date? Date { get; set; }
            /// <summary>End time</summary>
            [QueryParameter("end")]
            public DateTimeOffset? End { get; set; }
            /// <summary>SIGMET sequence number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sequence")]
            public string? Sequence { get; set; }
#nullable restore
#else
            [QueryParameter("sequence")]
            public string Sequence { get; set; }
#endif
            /// <summary>Start time</summary>
            [QueryParameter("start")]
            public DateTimeOffset? Start { get; set; }
        }
    }
}
