// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Alerts.Active.Zone.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Alerts.Active.Zone
{
    /// <summary>
    /// Builds and executes requests for operations under \alerts\active\zone
    /// </summary>
    public class ZoneRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaDemo.Clients.WeatherApi.alerts.active.zone.item collection</summary>
        /// <param name="position">NWS public zone/county identifier</param>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.Zone.Item.WithZoneItemRequestBuilder"/></returns>
        public KiotaDemo.Clients.WeatherApi.Alerts.Active.Zone.Item.WithZoneItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("zoneId", position);
                return new KiotaDemo.Clients.WeatherApi.Alerts.Active.Zone.Item.WithZoneItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.Zone.ZoneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ZoneRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/alerts/active/zone", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.Zone.ZoneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ZoneRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/alerts/active/zone", rawUrl)
        {
        }
    }
}
