// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Thumbnails.Satellite;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Thumbnails
{
    /// <summary>
    /// Builds and executes requests for operations under \thumbnails
    /// </summary>
    public class ThumbnailsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The satellite property</summary>
        public KiotaDemo.Clients.WeatherApi.Thumbnails.Satellite.SatelliteRequestBuilder Satellite
        {
            get => new KiotaDemo.Clients.WeatherApi.Thumbnails.Satellite.SatelliteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Thumbnails.ThumbnailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ThumbnailsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/thumbnails", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Thumbnails.ThumbnailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ThumbnailsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/thumbnails", rawUrl)
        {
        }
    }
}
