// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Radar.Profilers.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Radar.Profilers
{
    /// <summary>
    /// Builds and executes requests for operations under \radar\profilers
    /// </summary>
    public class ProfilersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaDemo.Clients.WeatherApi.radar.profilers.item collection</summary>
        /// <param name="position">Profiler station ID</param>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Radar.Profilers.Item.WithStationItemRequestBuilder"/></returns>
        public KiotaDemo.Clients.WeatherApi.Radar.Profilers.Item.WithStationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("stationId", position);
                return new KiotaDemo.Clients.WeatherApi.Radar.Profilers.Item.WithStationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Radar.Profilers.ProfilersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProfilersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar/profilers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Radar.Profilers.ProfilersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProfilersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar/profilers", rawUrl)
        {
        }
    }
}
