// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Radar.Profilers;
using KiotaDemo.Clients.WeatherApi.Radar.Queues;
using KiotaDemo.Clients.WeatherApi.Radar.Servers;
using KiotaDemo.Clients.WeatherApi.Radar.Stations;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Radar
{
    /// <summary>
    /// Builds and executes requests for operations under \radar
    /// </summary>
    public class RadarRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The profilers property</summary>
        public KiotaDemo.Clients.WeatherApi.Radar.Profilers.ProfilersRequestBuilder Profilers
        {
            get => new KiotaDemo.Clients.WeatherApi.Radar.Profilers.ProfilersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queues property</summary>
        public KiotaDemo.Clients.WeatherApi.Radar.Queues.QueuesRequestBuilder Queues
        {
            get => new KiotaDemo.Clients.WeatherApi.Radar.Queues.QueuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The servers property</summary>
        public KiotaDemo.Clients.WeatherApi.Radar.Servers.ServersRequestBuilder Servers
        {
            get => new KiotaDemo.Clients.WeatherApi.Radar.Servers.ServersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stations property</summary>
        public KiotaDemo.Clients.WeatherApi.Radar.Stations.StationsRequestBuilder Stations
        {
            get => new KiotaDemo.Clients.WeatherApi.Radar.Stations.StationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Radar.RadarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RadarRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Radar.RadarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RadarRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar", rawUrl)
        {
        }
    }
}
