// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Thumbnails.Satellite.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Thumbnails.Satellite
{
    /// <summary>
    /// Builds and executes requests for operations under \thumbnails\satellite
    /// </summary>
    public class SatelliteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaDemo.Clients.WeatherApi.thumbnails.satellite.item collection</summary>
        /// <param name="position">.</param>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Thumbnails.Satellite.Item.WithAreaItemRequestBuilder"/></returns>
        [Obsolete("")]
        public KiotaDemo.Clients.WeatherApi.Thumbnails.Satellite.Item.WithAreaItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("area", position);
                return new KiotaDemo.Clients.WeatherApi.Thumbnails.Satellite.Item.WithAreaItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Thumbnails.Satellite.SatelliteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SatelliteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/thumbnails/satellite", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Thumbnails.Satellite.SatelliteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SatelliteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/thumbnails/satellite", rawUrl)
        {
        }
    }
}
