// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Products.Locations.Item.Types;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Products.Locations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \products\locations\{locationId}
    /// </summary>
    public class WithLocationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The types property</summary>
        public KiotaDemo.Clients.WeatherApi.Products.Locations.Item.Types.TypesRequestBuilder Types
        {
            get => new KiotaDemo.Clients.WeatherApi.Products.Locations.Item.Types.TypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Products.Locations.Item.WithLocationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLocationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/products/locations/{locationId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Products.Locations.Item.WithLocationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLocationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/products/locations/{locationId}", rawUrl)
        {
        }
    }
}
