// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Alerts.Active.Area;
using KiotaDemo.Clients.WeatherApi.Alerts.Active.Count;
using KiotaDemo.Clients.WeatherApi.Alerts.Active.Region;
using KiotaDemo.Clients.WeatherApi.Alerts.Active.Zone;
using KiotaDemo.Clients.WeatherApi.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaDemo.Clients.WeatherApi.Alerts.Active
{
    /// <summary>
    /// Builds and executes requests for operations under \alerts\active
    /// </summary>
    public class ActiveRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The area property</summary>
        public KiotaDemo.Clients.WeatherApi.Alerts.Active.Area.AreaRequestBuilder Area
        {
            get => new KiotaDemo.Clients.WeatherApi.Alerts.Active.Area.AreaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The count property</summary>
        public KiotaDemo.Clients.WeatherApi.Alerts.Active.Count.CountRequestBuilder Count
        {
            get => new KiotaDemo.Clients.WeatherApi.Alerts.Active.Count.CountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The region property</summary>
        public KiotaDemo.Clients.WeatherApi.Alerts.Active.Region.RegionRequestBuilder Region
        {
            get => new KiotaDemo.Clients.WeatherApi.Alerts.Active.Region.RegionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The zone property</summary>
        public KiotaDemo.Clients.WeatherApi.Alerts.Active.Zone.ZoneRequestBuilder Zone
        {
            get => new KiotaDemo.Clients.WeatherApi.Alerts.Active.Zone.ZoneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.ActiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActiveRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/alerts/active{?area,certainty,code,event,limit*,message_type,point*,region,region_type*,severity,status,urgency,zone}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.ActiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActiveRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/alerts/active{?area,certainty,code,event,limit*,message_type,point*,region,region_type*,severity,status,urgency,zone}", rawUrl)
        {
        }
        /// <summary>
        /// Returns all currently active alerts
        /// </summary>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Models.AlertCollectionGeoJson"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaDemo.Clients.WeatherApi.Models.ProblemDetail">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaDemo.Clients.WeatherApi.Models.AlertCollectionGeoJson?> GetAsync(Action<RequestConfiguration<KiotaDemo.Clients.WeatherApi.Alerts.Active.ActiveRequestBuilder.ActiveRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaDemo.Clients.WeatherApi.Models.AlertCollectionGeoJson> GetAsync(Action<RequestConfiguration<KiotaDemo.Clients.WeatherApi.Alerts.Active.ActiveRequestBuilder.ActiveRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", KiotaDemo.Clients.WeatherApi.Models.ProblemDetail.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaDemo.Clients.WeatherApi.Models.AlertCollectionGeoJson>(requestInfo, KiotaDemo.Clients.WeatherApi.Models.AlertCollectionGeoJson.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns all currently active alerts
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<KiotaDemo.Clients.WeatherApi.Alerts.Active.ActiveRequestBuilder.ActiveRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<KiotaDemo.Clients.WeatherApi.Alerts.Active.ActiveRequestBuilder.ActiveRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/geo+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.ActiveRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaDemo.Clients.WeatherApi.Alerts.Active.ActiveRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaDemo.Clients.WeatherApi.Alerts.Active.ActiveRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns all currently active alerts
        /// </summary>
        public class ActiveRequestBuilderGetQueryParameters 
        {
            /// <summary>State/territory code or marine area codeThis parameter is incompatible with the following parameters: point, region, region_type, zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("area")]
            public string[]? Area { get; set; }
#nullable restore
#else
            [QueryParameter("area")]
            public string[] Area { get; set; }
#endif
            /// <summary>Certainty (observed, likely, possible, unlikely, unknown)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("certainty")]
            public KiotaDemo.Clients.WeatherApi.Models.AlertCertainty[]? Certainty { get; set; }
#nullable restore
#else
            [QueryParameter("certainty")]
            public KiotaDemo.Clients.WeatherApi.Models.AlertCertainty[] Certainty { get; set; }
#endif
            /// <summary>Event code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("code")]
            public string[]? Code { get; set; }
#nullable restore
#else
            [QueryParameter("code")]
            public string[] Code { get; set; }
#endif
            /// <summary>Event name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("event")]
            public string[]? Event { get; set; }
#nullable restore
#else
            [QueryParameter("event")]
            public string[] Event { get; set; }
#endif
            /// <summary>Limit</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Message type (alert, update, cancel)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("message_type")]
            public KiotaDemo.Clients.WeatherApi.Alerts.Active.GetMessage_typeQueryParameterType[]? MessageType { get; set; }
#nullable restore
#else
            [QueryParameter("message_type")]
            public KiotaDemo.Clients.WeatherApi.Alerts.Active.GetMessage_typeQueryParameterType[] MessageType { get; set; }
#endif
            /// <summary>Point (latitude,longitude)This parameter is incompatible with the following parameters: area, region, region_type, zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("point")]
            public string? Point { get; set; }
#nullable restore
#else
            [QueryParameter("point")]
            public string Point { get; set; }
#endif
            /// <summary>Marine region codeThis parameter is incompatible with the following parameters: area, point, region_type, zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("region")]
            public KiotaDemo.Clients.WeatherApi.Models.MarineRegionCode[]? Region { get; set; }
#nullable restore
#else
            [QueryParameter("region")]
            public KiotaDemo.Clients.WeatherApi.Models.MarineRegionCode[] Region { get; set; }
#endif
            /// <summary>Region type (land or marine)This parameter is incompatible with the following parameters: area, point, region, zone</summary>
            [QueryParameter("region_type")]
            public KiotaDemo.Clients.WeatherApi.Alerts.Active.GetRegion_typeQueryParameterType? RegionType { get; set; }
            /// <summary>Severity (extreme, severe, moderate, minor, unknown)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("severity")]
            public KiotaDemo.Clients.WeatherApi.Models.AlertSeverity[]? Severity { get; set; }
#nullable restore
#else
            [QueryParameter("severity")]
            public KiotaDemo.Clients.WeatherApi.Models.AlertSeverity[] Severity { get; set; }
#endif
            /// <summary>Status (actual, exercise, system, test, draft)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public KiotaDemo.Clients.WeatherApi.Alerts.Active.GetStatusQueryParameterType[]? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public KiotaDemo.Clients.WeatherApi.Alerts.Active.GetStatusQueryParameterType[] Status { get; set; }
#endif
            /// <summary>Urgency (immediate, expected, future, past, unknown)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("urgency")]
            public KiotaDemo.Clients.WeatherApi.Models.AlertUrgency[]? Urgency { get; set; }
#nullable restore
#else
            [QueryParameter("urgency")]
            public KiotaDemo.Clients.WeatherApi.Models.AlertUrgency[] Urgency { get; set; }
#endif
            /// <summary>Zone ID (forecast or county)This parameter is incompatible with the following parameters: area, point, region, region_type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("zone")]
            public string[]? Zone { get; set; }
#nullable restore
#else
            [QueryParameter("zone")]
            public string[] Zone { get; set; }
#endif
        }
    }
}
