// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Alerts.Active
{
    #pragma warning disable CS1591
    public enum GetRegion_typeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "land")]
        #pragma warning disable CS1591
        Land,
        #pragma warning restore CS1591
        [EnumMember(Value = "marine")]
        #pragma warning disable CS1591
        Marine,
        #pragma warning restore CS1591
    }
}
