// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Aviation.Cwsus;
using KiotaDemo.Clients.WeatherApi.Aviation.Sigmets;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Aviation
{
    /// <summary>
    /// Builds and executes requests for operations under \aviation
    /// </summary>
    public class AviationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cwsus property</summary>
        public KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.CwsusRequestBuilder Cwsus
        {
            get => new KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.CwsusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sigmets property</summary>
        public KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder Sigmets
        {
            get => new KiotaDemo.Clients.WeatherApi.Aviation.Sigmets.SigmetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Aviation.AviationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AviationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Aviation.AviationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AviationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation", rawUrl)
        {
        }
    }
}
