// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Alerts.Active.Region.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Alerts.Active.Region
{
    /// <summary>
    /// Builds and executes requests for operations under \alerts\active\region
    /// </summary>
    public class RegionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaDemo.Clients.WeatherApi.alerts.active.region.item collection</summary>
        /// <param name="position">Marine region ID</param>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.Region.Item.WithRegionItemRequestBuilder"/></returns>
        public KiotaDemo.Clients.WeatherApi.Alerts.Active.Region.Item.WithRegionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("region", position);
                return new KiotaDemo.Clients.WeatherApi.Alerts.Active.Region.Item.WithRegionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.Region.RegionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/alerts/active/region", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Alerts.Active.Region.RegionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/alerts/active/region", rawUrl)
        {
        }
    }
}
