// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum AlertUrgency
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Immediate")]
        #pragma warning disable CS1591
        Immediate,
        #pragma warning restore CS1591
        [EnumMember(Value = "Expected")]
        #pragma warning disable CS1591
        Expected,
        #pragma warning restore CS1591
        [EnumMember(Value = "Future")]
        #pragma warning disable CS1591
        Future,
        #pragma warning restore CS1591
        [EnumMember(Value = "Past")]
        #pragma warning disable CS1591
        Past,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
