// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum AlertCollectionGeoJson_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "FeatureCollection")]
        #pragma warning disable CS1591
        FeatureCollection,
        #pragma warning restore CS1591
    }
}
