// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum GeoJsonGeometryMember1_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Point")]
        #pragma warning disable CS1591
        Point,
        #pragma warning restore CS1591
    }
}
