// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public class GeoJsonGeometryMember3 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A GeoJSON bounding box. Please refer to IETF RFC 7946 for information on the GeoJSON format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? Bbox { get; set; }
#nullable restore
#else
        public List<double?> Bbox { get; set; }
#endif
        /// <summary>A GeoJSON polygon. Please refer to IETF RFC 7946 for information on the GeoJSON format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Coordinates { get; set; }
#nullable restore
#else
        public UntypedNode Coordinates { get; set; }
#endif
        /// <summary>The type property</summary>
        public KiotaDemo.Clients.WeatherApi.Models.GeoJsonGeometryMember3_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Models.GeoJsonGeometryMember3"/> and sets the default values.
        /// </summary>
        public GeoJsonGeometryMember3()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Models.GeoJsonGeometryMember3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static KiotaDemo.Clients.WeatherApi.Models.GeoJsonGeometryMember3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaDemo.Clients.WeatherApi.Models.GeoJsonGeometryMember3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bbox", n => { Bbox = n.GetCollectionOfPrimitiveValues<double?>()?.ToList(); } },
                { "coordinates", n => { Coordinates = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<KiotaDemo.Clients.WeatherApi.Models.GeoJsonGeometryMember3_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<double?>("bbox", Bbox);
            writer.WriteObjectValue<UntypedNode>("coordinates", Coordinates);
            writer.WriteEnumValue<KiotaDemo.Clients.WeatherApi.Models.GeoJsonGeometryMember3_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
