// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum GeoJsonGeometryMember2_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "LineString")]
        #pragma warning disable CS1591
        LineString,
        #pragma warning restore CS1591
    }
}
