// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum GeoJsonGeometryMember5_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "MultiLineString")]
        #pragma warning disable CS1591
        MultiLineString,
        #pragma warning restore CS1591
    }
}
