// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum GeoJsonGeometryMember3_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Polygon")]
        #pragma warning disable CS1591
        Polygon,
        #pragma warning restore CS1591
    }
}
