// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum GeoJsonFeature_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Feature")]
        #pragma warning disable CS1591
        Feature,
        #pragma warning restore CS1591
    }
}
