// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum GeoJsonGeometryMember4_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "MultiPoint")]
        #pragma warning disable CS1591
        MultiPoint,
        #pragma warning restore CS1591
    }
}
