// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum Gridpoint_Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "wx:Gridpoint")]
        #pragma warning disable CS1591
        WxGridpoint,
        #pragma warning restore CS1591
    }
}
