// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    /// <summary>If not null, indicates a non-diurnal temperature trend for the period (either rising temperature overnight, or falling temperature during the day)</summary>
    public enum GridpointForecastPeriod_temperatureTrend
    {
        [EnumMember(Value = "rising")]
        #pragma warning disable CS1591
        Rising,
        #pragma warning restore CS1591
        [EnumMember(Value = "falling")]
        #pragma warning disable CS1591
        Falling,
        #pragma warning restore CS1591
    }
}
