// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum Gridpoint_weather_values_value_intensity
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "very_light")]
        #pragma warning disable CS1591
        Very_light,
        #pragma warning restore CS1591
        [EnumMember(Value = "light")]
        #pragma warning disable CS1591
        Light,
        #pragma warning restore CS1591
        [EnumMember(Value = "moderate")]
        #pragma warning disable CS1591
        Moderate,
        #pragma warning restore CS1591
        [EnumMember(Value = "heavy")]
        #pragma warning disable CS1591
        Heavy,
        #pragma warning restore CS1591
    }
}
