// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    /// <summary>Denotes the units used in the textual portions of the forecast.</summary>
    public enum GridpointForecastUnits
    {
        [EnumMember(Value = "us")]
        #pragma warning disable CS1591
        Us,
        #pragma warning restore CS1591
        [EnumMember(Value = "si")]
        #pragma warning disable CS1591
        Si,
        #pragma warning restore CS1591
    }
}
