// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum MetarPhenomenon_modifier
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "patches")]
        #pragma warning disable CS1591
        Patches,
        #pragma warning restore CS1591
        [EnumMember(Value = "blowing")]
        #pragma warning disable CS1591
        Blowing,
        #pragma warning restore CS1591
        [EnumMember(Value = "low_drifting")]
        #pragma warning disable CS1591
        Low_drifting,
        #pragma warning restore CS1591
        [EnumMember(Value = "freezing")]
        #pragma warning disable CS1591
        Freezing,
        #pragma warning restore CS1591
        [EnumMember(Value = "shallow")]
        #pragma warning disable CS1591
        Shallow,
        #pragma warning restore CS1591
        [EnumMember(Value = "partial")]
        #pragma warning disable CS1591
        Partial,
        #pragma warning restore CS1591
        [EnumMember(Value = "showers")]
        #pragma warning disable CS1591
        Showers,
        #pragma warning restore CS1591
    }
}
