// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum Observation_Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "wx:ObservationStation")]
        #pragma warning disable CS1591
        WxObservationStation,
        #pragma warning restore CS1591
    }
}
