// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public class ObservationStationCollectionGeoJson : KiotaDemo.Clients.WeatherApi.Models.GeoJsonFeatureCollection, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The observationStations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ObservationStations { get; set; }
#nullable restore
#else
        public List<string> ObservationStations { get; set; }
#endif
        /// <summary>Links for retrieving more data from paged data sets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaDemo.Clients.WeatherApi.Models.PaginationInfo? Pagination { get; set; }
#nullable restore
#else
        public KiotaDemo.Clients.WeatherApi.Models.PaginationInfo Pagination { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Models.ObservationStationCollectionGeoJson"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new KiotaDemo.Clients.WeatherApi.Models.ObservationStationCollectionGeoJson CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaDemo.Clients.WeatherApi.Models.ObservationStationCollectionGeoJson();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "observationStations", n => { ObservationStations = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                { "pagination", n => { Pagination = n.GetObjectValue<KiotaDemo.Clients.WeatherApi.Models.PaginationInfo>(KiotaDemo.Clients.WeatherApi.Models.PaginationInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfPrimitiveValues<string>("observationStations", ObservationStations);
            writer.WriteObjectValue<KiotaDemo.Clients.WeatherApi.Models.PaginationInfo>("pagination", Pagination);
        }
    }
}
