// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum Office_address_Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PostalAddress")]
        #pragma warning disable CS1591
        PostalAddress,
        #pragma warning restore CS1591
    }
}
