// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum Point_Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "wx:Point")]
        #pragma warning disable CS1591
        WxPoint,
        #pragma warning restore CS1591
    }
}
