// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaDemo.Clients.WeatherApi.Models
{
    #pragma warning disable CS1591
    public enum Zone_Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "wx:Zone")]
        #pragma warning disable CS1591
        WxZone,
        #pragma warning restore CS1591
    }
}
