// <auto-generated/>
using KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item.Cwas.Item.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item.Cwas.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \aviation\cwsus\{cwsuId}\cwas\{date}
    /// </summary>
    public class WithDateItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaDemo.Clients.WeatherApi.aviation.cwsus.item.cwas.item.item collection</summary>
        /// <param name="position">Sequence number</param>
        /// <returns>A <see cref="KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item.Cwas.Item.Item.WithSequenceItemRequestBuilder"/></returns>
        public KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item.Cwas.Item.Item.WithSequenceItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("sequence", position);
                return new KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item.Cwas.Item.Item.WithSequenceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item.Cwas.Item.WithDateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDateItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation/cwsus/{cwsuId}/cwas/{date}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaDemo.Clients.WeatherApi.Aviation.Cwsus.Item.Cwas.Item.WithDateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDateItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aviation/cwsus/{cwsuId}/cwas/{date}", rawUrl)
        {
        }
    }
}
